# Generated by Django 4.0.2 on 2022-09-04 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfin', '0002_newuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
