# Generated by Django 4.0.2 on 2022-10-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfin', '0003_rename_user_id_newuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='access_token',
            field=models.CharField(default='no_access_token', max_length=60, verbose_name='Access_Token'),
        ),
    ]
