# Generated by Django 4.0.2 on 2022-10-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfin', '0004_newuser_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(default='not_provided', max_length=12, verbose_name='Phone Number'),
        ),
    ]
